/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import probabilidad.Datos;
import probabilidad.Hipergeometrica;
import probabilidad.Binomial;
import forms.JFBinomial;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eloic
 */
public class JFMain extends javax.swing.JFrame {

    /**
     * Creates new form JFMain
     */
    public JFMain() {
        initComponents();
        ButtonGroup grupoBotones = new ButtonGroup();
        grupoBotones.add(jrExacta);
        grupoBotones.add(jrAHasta);
        grupoBotones.add(jrAMenor);
        grupoBotones.add(jrAcu);
        grupoBotones.add(jrAMayor);
    }

    private void c_binomial(int poblacion, int muestra, int exitos_rango, double prob_exito, double prob_fracaso) {
        Binomial binomial = new Binomial(poblacion, muestra, exitos_rango, prob_exito, prob_fracaso);
        

    }

    private void c_hipergeometrica(int poblacion, int muestra, int exitos_rango, int exitos_poblacion) {
        Hipergeometrica hipergeometrica = new Hipergeometrica(poblacion, muestra, exitos_rango, exitos_poblacion);
        System.out.println("PROBABILIDAD: "+hipergeometrica.calcularProbabilidad());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtxtN = new javax.swing.JTextField();
        jtxtP = new javax.swing.JTextField();
        jtxtX = new javax.swing.JTextField();
        jtxtNN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jrExacta = new javax.swing.JRadioButton();
        jrAHasta = new javax.swing.JRadioButton();
        jrAMenor = new javax.swing.JRadioButton();
        jrAcu = new javax.swing.JRadioButton();
        jrAMayor = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jtxtQ = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtK = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setText("Muestra (n):");

        jLabel2.setText("Probabilidad de exito (p):");

        jLabel3.setText("Exitos (x):");

        jLabel4.setText("Tamaño de la poblacion (N):");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Resultados:");

        jrExacta.setText("Probabilidad exacta X =");

        jrAHasta.setText("Probabilidad acumulada hasta   X <= ");

        jrAMenor.setText("Probabilidad acumulada menor que  X <");

        jrAcu.setText("Probabilidad acumulada desde  X >=");

        jrAMayor.setText("Probabilidad acumulada mayor que  X >");

        jLabel6.setText("Probabilidad de Fracaso (q): ");

        jLabel7.setText("Numero de Individuos (K): ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(331, 331, 331))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxtP, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                .addComponent(jtxtQ))
                            .addComponent(jtxtN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtX, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtNN, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(jtxtK))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrExacta)
                    .addComponent(jrAHasta)
                    .addComponent(jrAMenor)
                    .addComponent(jrAcu)
                    .addComponent(jrAMayor))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrExacta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrAHasta)
                    .addComponent(jtxtP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrAMenor)
                    .addComponent(jLabel6)
                    .addComponent(jtxtQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrAcu)
                    .addComponent(jLabel3)
                    .addComponent(jtxtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrAMayor)
                    .addComponent(jLabel4)
                    .addComponent(jtxtNN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int poblacion = 0, muestra = 0, exitos_rango = 0, exitos_poblacion = 0;
        double prob_exito = 0, prob_fracaso = 0;

        try {
            poblacion = jtxtNN.getText().isEmpty() ? 0 : Integer.parseInt(jtxtNN.getText());
            muestra = jtxtN.getText().isEmpty() ? 0 : Integer.parseInt(jtxtN.getText());
            exitos_rango = jtxtX.getText().isEmpty() ? 0 : Integer.parseInt(jtxtX.getText());
            exitos_poblacion = jtxtK.getText().isEmpty() ? 0 : Integer.parseInt(jtxtK.getText());
            prob_exito = jtxtP.getText().isEmpty() ? 0 : Double.parseDouble(jtxtP.getText());
            prob_fracaso = jtxtQ.getText().isEmpty() ? 0 : Double.parseDouble(jtxtQ.getText());
        } catch (NumberFormatException e) {
            System.err.println("Error: Ingrese valores numéricos válidos.");
            return; // Detiene la ejecución si hay un error en la conversión
        }

        // Evitar división por cero
        double verificacion_formula = (poblacion != 0) ? ((double) muestra / poblacion) : 0;

        if (verificacion_formula >= 0.2) {
            System.out.println("HIPERGEOMETRICA");
            c_hipergeometrica( poblacion,  muestra,  exitos_rango,  exitos_poblacion);
        } else {
            System.out.println("BINOMIAL");
            c_binomial( poblacion,  muestra,  exitos_rango,  prob_exito,  prob_fracaso);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jrAHasta;
    private javax.swing.JRadioButton jrAMayor;
    private javax.swing.JRadioButton jrAMenor;
    private javax.swing.JRadioButton jrAcu;
    private javax.swing.JRadioButton jrExacta;
    private javax.swing.JTextField jtxtK;
    private javax.swing.JTextField jtxtN;
    private javax.swing.JTextField jtxtNN;
    private javax.swing.JTextField jtxtP;
    private javax.swing.JTextField jtxtQ;
    private javax.swing.JTextField jtxtX;
    // End of variables declaration//GEN-END:variables
}
